services:
  db:
    image: postgres:16.2-alpine
    container_name: sr_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: smart_recruiter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smart_recruiter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: